import type { Product, Category } from './api';

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Базовые покрытия', slug: 'bazovye_pokrytiya' },
  { id: '2', name: 'Цветные гель-лаки', slug: 'tsvetnye_gel_laki' },
  { id: '3', name: 'Топовые покрытия', slug: 'topovye_pokrytiya' },
  { id: '4', name: 'Камуфляжи', slug: 'kamuflyazhi' },
  { id: '5', name: 'Гели для наращивания', slug: 'geli_dlya_narashchivaniya' },
  { id: '6', name: 'Must have', slug: 'must_have' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'BASE GEL 15 ML',
    sku: 'AC-BG-15',
    slug: '198',
    description:
      'Базовое покрытие для гель-лака. Обеспечивает надёжное сцепление с натуральным ногтем.',
    price: 1100,
    wholesale_price: 770,
    weight: 0.03,
    volume: 0.000015,
    length: 80,
    width: 30,
    height: 30,
    bp_available: 150,
    category: { id: '1', name: 'Базовые покрытия', slug: 'bazovye_pokrytiya' },
    images: [
      { id: 'img-1-1', file_path: 'base-gel-15-1.png', sort: 0 },
      { id: 'img-1-2', file_path: 'base-gel-15-2.png', sort: 1 },
    ],
    date_created: '2025-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'TOP COAT MATTE 15 ML',
    sku: 'AC-TM-15',
    slug: '200',
    description: 'Матовое топовое покрытие. Стойкое бархатистое покрытие без липкого слоя.',
    price: 1200,
    wholesale_price: 840,
    weight: 0.03,
    volume: 0.000015,
    length: 80,
    width: 30,
    height: 30,
    bp_available: 85,
    category: { id: '3', name: 'Топовые покрытия', slug: 'topovye_pokrytiya' },
    images: [{ id: 'img-2-1', file_path: 'top-matte-15-1.png', sort: 0 }],
    date_created: '2025-02-10T10:00:00Z',
  },
  {
    id: '3',
    name: 'COLOR GEL #001 RED PASSION',
    sku: 'AC-CG-001',
    slug: '354',
    description: 'Насыщенный красный гель-лак. Плотное покрытие в 2 слоя.',
    price: 950,
    wholesale_price: 665,
    weight: 0.025,
    volume: 0.000015,
    length: 75,
    width: 25,
    height: 25,
    bp_available: 200,
    category: { id: '2', name: 'Цветные гель-лаки', slug: 'tsvetnye_gel_laki' },
    images: [],
    date_created: '2025-03-01T10:00:00Z',
  },
  {
    id: '4',
    name: 'COLOR GEL #002 NUDE ROSE',
    sku: 'AC-CG-002',
    slug: '355',
    description: 'Нежный нюдовый розовый. Идеален для французского маникюра.',
    price: 950,
    wholesale_price: 665,
    weight: 0.025,
    volume: 0.000015,
    length: 75,
    width: 25,
    height: 25,
    bp_available: 180,
    category: { id: '2', name: 'Цветные гель-лаки', slug: 'tsvetnye_gel_laki' },
    images: [],
    date_created: '2025-03-01T10:00:00Z',
  },
  {
    id: '5',
    name: 'ACRYLATE GEL 30 ML',
    sku: 'AC-AG-30',
    slug: '345',
    description: 'Акрилатик для наращивания ногтей. Самовыравнивающийся, средней вязкости.',
    price: 1800,
    wholesale_price: 1260,
    weight: 0.05,
    volume: 0.00003,
    length: 90,
    width: 35,
    height: 35,
    bp_available: 60,
    category: { id: '5', name: 'Гели для наращивания', slug: 'geli_dlya_narashchivaniya' },
    images: [
      { id: 'img-5-1', file_path: 'acrylate-gel-30-1.png', sort: 0 },
      { id: 'img-5-2', file_path: 'acrylate-gel-30-2.png', sort: 1 },
      { id: 'img-5-3', file_path: 'acrylate-gel-30-3.png', sort: 2 },
    ],
    date_created: '2025-01-20T10:00:00Z',
  },
  {
    id: '6',
    name: 'CAMOUFLAGE BASE #01 PEACH',
    sku: 'AC-CB-01',
    slug: '226',
    description:
      'Камуфляжная база персикового оттенка. Идеальна для выравнивания ногтевой пластины.',
    price: 1300,
    wholesale_price: 910,
    weight: 0.03,
    volume: 0.000015,
    length: 80,
    width: 30,
    height: 30,
    bp_available: 120,
    category: { id: '4', name: 'Камуфляжи', slug: 'kamuflyazhi' },
    images: [],
    date_created: '2025-02-15T10:00:00Z',
  },
  {
    id: '7',
    name: 'TOP COAT GLOSSY 15 ML',
    sku: 'AC-TG-15',
    slug: '205',
    description: 'Глянцевое топовое покрытие без липкого слоя. Ультра-блеск.',
    price: 1200,
    wholesale_price: 840,
    weight: 0.03,
    volume: 0.000015,
    length: 80,
    width: 30,
    height: 30,
    bp_available: 95,
    category: { id: '3', name: 'Топовые покрытия', slug: 'topovye_pokrytiya' },
    images: [],
    date_created: '2025-01-10T10:00:00Z',
  },
  {
    id: '8',
    name: 'COLOR GEL #003 DEEP BLUE',
    sku: 'AC-CG-003',
    slug: '283',
    description: 'Глубокий синий гель-лак. Полное перекрытие в 2 слоя.',
    price: 950,
    wholesale_price: 665,
    weight: 0.025,
    volume: 0.000015,
    length: 75,
    width: 25,
    height: 25,
    bp_available: 0,
    category: { id: '2', name: 'Цветные гель-лаки', slug: 'tsvetnye_gel_laki' },
    images: [],
    date_created: '2025-03-05T10:00:00Z',
  },
  {
    id: '9',
    name: 'RUBBER BASE 30 ML',
    sku: 'AC-RB-30',
    slug: '207',
    description: 'Каучуковая база. Густая консистенция для выравнивания.',
    price: 1500,
    wholesale_price: 1050,
    weight: 0.05,
    volume: 0.00003,
    length: 90,
    width: 35,
    height: 35,
    bp_available: 45,
    category: { id: '1', name: 'Базовые покрытия', slug: 'bazovye_pokrytiya' },
    images: [],
    date_created: '2025-02-20T10:00:00Z',
  },
];
